adding vans
NickBansal/jessie-react pull request #1
Opened 2024-08-16 12:50 UTC by jessie-pann

2024-08-21 10:20 UTC, NickBansal requested changes

2024-08-21 10:20 UTC, NickBansal commented on eslint.config.mjs
> +import globals from "globals";
hmmmm did you mean to create this file? we do have an eslint file already set up

2024-08-21 10:20 UTC, NickBansal commented on src/App.tsx
> +      </Routes> */}
we can delete this commented out code if its not needed

2024-08-22 09:10 UTC, jessie-pann commented on src/App.tsx
> +      </Routes> */}
i'v deleted the commented out code in my latest commitment

2024-08-23 09:52 UTC, NickBansal approved these changes

2024-08-30 08:42 UTC, merged